### PR TITLE
fix #155: allow main_frame requests for links

### LINKED ISSUE #155: Links to domains in the block-list are broken
STR:
1. Go to davidwalsh.name (or economist.com)
2. Click the twitter icon/link

Expected results:
Should go to twitter.com

Actual results:
Blank browser page because the request is blocked

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

**Comment by groovecoder** [comment]
@pdehaan LMK when this looks good. I'll add an rc10 signed .xpi and merge.

**Comment by pdehaan** [comment]
Built locally and so far everything looks good. I think we're fine to merge and roll with this and file follow up issues if we notice anything else. 👍 

Thanks for the quick turnaround on this!

**Comment by pdehaan** [comment]
I APPROVE!

(but yeah, let's build that new XPI and add it to artifacts and get that pushed onto the dev server for other travellers).

**Comment by groovecoder** [comment]
Updated with signed `blok-1.0rc10.xpi` in `web-ext-artifacts/`

**Pull request merged**
