### PR TITLE
Add LICENSE file

### PR DESCRIPTION
**Pull request by pdehaan**
Adding top level LICENSE file.

Approvals received from:
* [x] @groovecoder
* [x] @pdehaan 
* [x] @rbillings

### CODE REVIEW

**Comment by groovecoder** [comment]
When we've added this on previous projects, we [used the PR to collect license agreement from all existing contributors](https://github.com/mozilla/kuma/pull/1000#issuecomment-17811789) as a proper paper-trail of license.

So ... @pdehaan, @rbillings: add a comment with the following text:

"I give my permission to license under the MPL 2 any contributions I have made to the Kuma codebase."

?

**Comment by groovecoder** [comment]
I give my permission to license under the MPL 2 any contributions I have made to the Blok codebase.

**Comment by rbillings** [comment]
I give my permission to license under the MPL 2 any contributions I have made to the Blok codebase.

**Comment by pdehaan** [comment]
I give my permission to license under the MPL 2 any contributions I have made to the Blok codebase.

**Comment by pdehaan** [comment]
3/3, self merging.

**Pull request merged**
