### PR TITLE
Replace addons-linter with 'web-ext lint'

### PR DESCRIPTION
**Pull request by pdehaan**
Yay for removing dependencies!

r? @groovecoder

### CODE REVIEW

**Comment by groovecoder** [comment]
Will check it out ...

**Comment by groovecoder** [comment]
😦 Now I'm getting the `dispensary` error I was getting when I tried to run `addons-linter` directly ...
```
lcrouch:blok lcrouch$ nvm use stable
Now using node v6.3.1 (npm v3.10.3)
lcrouch:blok lcrouch$ ./node_modules/.bin/web-ext lint
Error: Cannot find module 'dispensary'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.module.exports.Object.defineProperty.value (/Users/lcrouch/code/blok/node_modules/addons-linter/dist/webpack:/external "dispensary":1:1)
    at __webpack_require__ (/Users/lcrouch/code/blok/node_modules/addons-linter/dist/webpack:/webpack/bootstrap c0f1533249da522d5b10:19:1)
    at Object.<anonymous> (/Users/lcrouch/code/blok/node_modules/addons-linter/dist/webpack:/src/linter.js:5:1)
    at __webpack_require__ (/Users/lcrouch/code/blok/node_modules/addons-linter/dist/webpack:/webpack/bootstrap c0f1533249da522d5b10:19:1)
    at Object.module.exports.Object.defineProperty.value (/Users/lcrouch/code/blok/node_modules/addons-linter/dist/webpack:/src/main.js:2:1)
    at __webpack_require__ (/Users/lcrouch/code/blok/node_modules/addons-linter/dist/webpack:/webpack/bootstrap c0f1533249da522d5b10:19:1)
```
Note: `web-ext` has `addons-linter` as a dependency, so this doesn't really *remove* a dependency.

**Comment by groovecoder** [comment]
Also:
```
lcrouch:blok lcrouch$ npm i dispensary
blok@1.0.0 /Users/lcrouch/code/blok
└─┬ web-ext@1.4.0
  └─┬ addons-linter@0.14.4
    └── dispensary@0.7.0

lcrouch:blok lcrouch$ ./node_modules/.bin/web-ext lint
Error: Cannot find module 'dispensary'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.module.exports.Object.defineProperty.value (/Users/lcrouch/code/blok/node_modules/addons-linter/dist/webpack:/external "dispensary":1:1)
    at __webpack_require__ (/Users/lcrouch/code/blok/node_modules/addons-linter/dist/webpack:/webpack/bootstrap c0f1533249da522d5b10:19:1)
    at Object.<anonymous> (/Users/lcrouch/code/blok/node_modules/addons-linter/dist/webpack:/src/linter.js:5:1)
    at __webpack_require__ (/Users/lcrouch/code/blok/node_modules/addons-linter/dist/webpack:/webpack/bootstrap c0f1533249da522d5b10:19:1)
    at Object.module.exports.Object.defineProperty.value (/Users/lcrouch/code/blok/node_modules/addons-linter/dist/webpack:/src/main.js:2:1)
    at __webpack_require__ (/Users/lcrouch/code/blok/node_modules/addons-linter/dist/webpack:/webpack/bootstrap c0f1533249da522d5b10:19:1)
```

**Comment by pdehaan** [comment]
Weird... And did you do a scorched-earth caliber `$ rm -rf node_modules && npm i` to flush all the old node_modules that may have been lingering?

**Comment by groovecoder** [comment]
```
lcrouch:blok lcrouch$ nvm use stable
Now using node v6.3.1 (npm v3.10.3)
lcrouch:blok lcrouch$ rm -rf node_modules
lcrouch:blok lcrouch$ npm i
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

> dtrace-provider@0.6.0 install /Users/lcrouch/code/blok/node_modules/dtrace-provider
> node scripts/install.js


> fsevents@1.0.14 install /Users/lcrouch/code/blok/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/lcrouch/code/blok/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" is installed via remote

> spawn-sync@1.0.15 postinstall /Users/lcrouch/code/blok/node_modules/spawn-sync
> node postinstall


> blok@1.0.0 postinstall /Users/lcrouch/code/blok
> cp ./node_modules/foundation-sites/dist/foundation.min.css ./css/foundation.min.css

blok@1.0.0 /Users/lcrouch/code/blok
├─┬ browserify@13.0.1
│ ├── assert@1.3.0
...
lcrouch:blok lcrouch$ ./node_modules/.bin/web-ext lint
Error: Cannot find module 'dispensary'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.module.exports.Object.defineProperty.value (/Users/lcrouch/code/blok/node_modules/addons-linter/dist/webpack:/external "dispensary":1:1)
    at __webpack_require__ (/Users/lcrouch/code/blok/node_modules/addons-linter/dist/webpack:/webpack/bootstrap c0f1533249da522d5b10:19:1)
    at Object.<anonymous> (/Users/lcrouch/code/blok/node_modules/addons-linter/dist/webpack:/src/linter.js:5:1)
    at __webpack_require__ (/Users/lcrouch/code/blok/node_modules/addons-linter/dist/webpack:/webpack/bootstrap c0f1533249da522d5b10:19:1)
    at Object.module.exports.Object.defineProperty.value (/Users/lcrouch/code/blok/node_modules/addons-linter/dist/webpack:/src/main.js:2:1)
    at __webpack_require__ (/Users/lcrouch/code/blok/node_modules/addons-linter/dist/webpack:/webpack/bootstrap c0f1533249da522d5b10:19:1)
```

**Comment by pdehaan** [comment]
Inconceivable!

```
$ node --version && npm --version
v6.3.0
3.10.3
```

Feel free to close this. It seemingly works "fine" as-is, and it looks like you have some super wack nvm setup over there.

```
$ nvm --version
0.25.4
```

Maybe I'll try nuking my nvm from orbit and reinstalling to latest version (which seems to be 0.31.4, per https://github.com/creationix/nvm/blob/master/package.json).

**Comment by pdehaan** [comment]
I'm starting to think you're feeling _less than amazed(tm)_ at this point.

**Comment by pdehaan** [comment]
I'm starting to think it's you.



I just did a fresh install of **nvm** using https://github.com/creationix/nvm#install-script (hooray for `curl | bash`) and then did a fresh `git clone` and `npm i` using node@6.3.0 and everything worked.

```sh
$ git clone git@github.com:pdehaan/blok.git --branch remove-addons-linter
$ cd blok
$ nvm --version # 0.31.4
$ nvm use 6 # Now using node v6.3.0 (npm v3.10.3)
$ node --version # v6.3.0
$ npm --version # 3.10.3
$ npm i
...

$ ./node_modules/.bin/web-ext lint

Validation Summary:

errors          0
notices         0
warnings        0
```

**Comment by pdehaan** [comment]
I'm running out of ideas (and GIFs), but you may also want to try nuking your local npm cache and see if that helps: https://docs.npmjs.com/cli/cache

```sh
$ npm cache clean
```

May work. May not. May break everything. Software is fun! 

I'd also try making sure your nvm is up to date.
Only other thing I can think of is to delete your installed Node 6 via nvm and reinstall, but now I'm just throwing out stupidity.

**Comment by groovecoder** [comment]
Either `npm cache clean` did it ... or the fact that I got a new computer over the weekend. But this looks good now.

**Pull request merged**
