### PR TITLE
Add ESLint and fix a few formatting errors

### PR DESCRIPTION
**Pull request by groovecoder**
Supersedes https://github.com/mozilla/blok/pull/33 with a rebase.

### CODE REVIEW

**Comment by pdehaan** [comment]
Once this lands, I can convert to the **eslint-config-standard** config from #40 and submit a new PR (with the errors downgraded to warnings so I don't fail Travis-CI).

**Comment by groovecoder** [comment]
For me, the appeal for standard over eslint is that Standard doesn't require a config file. So if we're going with standard code style, I'd prefer to just drop eslint altogether unless we have a reason to do so.

One such reason could be that other Mozilla (add-ons) JS code-bases use a common eslint configuration. If that's the case, I'd love to adopt that.

If that's not the case, can we just switch to standard and drop eslint altogether?

**Comment by pdehaan** [comment]
Sure, we could drop ESLint and just use Standard if you want.
Probably just need to add our globals into the package.json `standard` config object:

```js
  "standard": {
    "globals": [
      "BroadcastChannel",
      "browser",
      "fetch",
      "URL"
    ]
  }
```

Running `$ standard` seems to work roughly the same as ESLint (albeit with a less glorious reporter):

```js
 $ ./node_modules/.bin/standard

standard: Use JavaScript Standard Style (http://standardjs.com)
  /Users/pdehaan/dev/github/mozilla/blok/js/background.js:9:5: Identifier 'current_active_tab_id' is not in camel case.
  /Users/pdehaan/dev/github/mozilla/blok/js/background.js:10:5: Identifier 'current_origin_disabled_index' is not in camel case.
  /Users/pdehaan/dev/github/mozilla/blok/js/background.js:11:5: Identifier 'current_active_origin' is not in camel case.
  /Users/pdehaan/dev/github/mozilla/blok/js/background.js:12:5: Identifier 'blocked_requests' is not in camel case.
  /Users/pdehaan/dev/github/mozilla/blok/js/background.js:13:5: Identifier 'blocked_entities' is not in camel case.
  /Users/pdehaan/dev/github/mozilla/blok/js/background.js:14:5: Identifier 'allowed_requests' is not in camel case.
  /Users/pdehaan/dev/github/mozilla/blok/js/background.js:15:5: Identifier 'allowed_entities' is not in camel case.
  /Users/pdehaan/dev/github/mozilla/blok/js/background.js:16:5: Identifier 'total_exec_time' is not in camel case.
  /Users/pdehaan/dev/github/mozilla/blok/js/background.js:17:5: Identifier 'reasons_given' is not in camel case.
  /Users/pdehaan/dev/github/mozilla/blok/js/background.js:49:5: Identifier 'current_active_origin' is not in camel case.
  /Users/pdehaan/dev/github/mozilla/blok/js/background.js:50:5: Identifier 'current_origin_disabled_index' is not in camel case.
  /Users/pdehaan/dev/github/mozilla/blok/js/background.js:56:29: Identifier 'current_origin_disabled_index' is not in camel case.
  /Users/pdehaan/dev/github/mozilla/blok/js/background.js:172:5: Identifier 'current_active_tab_id' is not in camel case.
  /Users/pdehaan/dev/github/mozilla/blok/js/background.js:179:11: 'actionPerformed' is defined but never used
  /Users/pdehaan/dev/github/mozilla/blok/js/background.js:179:30: Identifier 'current_origin_disabled_index' is not in camel case.
  /Users/pdehaan/dev/github/mozilla/blok/js/background.js:180:29: Identifier 'current_origin_disabled_index' is not in camel case.
  /Users/pdehaan/dev/github/mozilla/blok/js/background.js:181:29: Identifier 'current_origin_disabled_index' is not in camel case.
  /Users/pdehaan/dev/github/mozilla/blok/js/canonicalize.js:1:70: Unnecessary escape character: \.
  /Users/pdehaan/dev/github/mozilla/blok/js/canonicalize.js:2:45: Unnecessary escape character: \.
  /Users/pdehaan/dev/github/mozilla/blok/js/canonicalize.js:3:71: Unnecessary escape character: \.
  /Users/pdehaan/dev/github/mozilla/blok/js/canonicalize.js:19:62: Unnecessary escape character: \.
  /Users/pdehaan/dev/github/mozilla/blok/js/canonicalize.js:26:7: 'isIP4Decimal' is defined but never used
  /Users/pdehaan/dev/github/mozilla/blok/js/lists.js:37:12: Identifier 'category_name' is not in camel case.
  /Users/pdehaan/dev/github/mozilla/blok/js/lists.js:39:9: Identifier 'entity_count' is not in camel case.
  /Users/pdehaan/dev/github/mozilla/blok/js/lists.js:41:25: Identifier 'entity_count' is not in camel case.
  /Users/pdehaan/dev/github/mozilla/blok/js/lists.js:44:16: Identifier 'entity_name' is not in camel case.
  /Users/pdehaan/dev/github/mozilla/blok/js/lists.js:47:18: Identifier 'main_domain' is not in camel case.
  /Users/pdehaan/dev/github/mozilla/blok/js/lists.js:50:15: Identifier 'domains_count' is not in camel case.
  /Users/pdehaan/dev/github/mozilla/blok/js/lists.js:52:31: Identifier 'domains_count' is not in camel case.
  /Users/pdehaan/dev/github/mozilla/blok/js/lists.js:53:37: Identifier 'main_domain' is not in camel case.


$ echo $? # 1
```

So as long as we can fix all the camel-case errors, I think it would be fine. If we need to tweak Standard rules, it looks like the recommendation is to go with the ESLint and Standard route, per http://standardjs.com/#can-you-make-rule-x-configurable.

**Comment by groovecoder** [comment]
Let's go for the plain Standard now then. I was wanting to do it after I got other outstanding PRs merged, and now I have. Do you want to change this branch/PR to Standard, or just start a new branch for it, or want me to do it?

**Comment by groovecoder** [comment]
Can we close this one now that https://github.com/mozilla/blok/pull/41 is in?

**Comment by pdehaan** [comment]
Closing in favor of #41 (using `standard` directly instead of via ESLint plugin/config).

**Pull request closed without merging**
