### PR TITLE
fix #147: breakage-notes-panel for single height

### LINKED ISSUE #147: "Submit" button is missing from the "Report a problem" panel on Ubuntu (16.04 x64)
[Affected versions]:
- Nightly 51.0a1
- Blok v0.1.0rc3

[Affected Platforms]:
- All Linux

[Prerequisites]:
- Latest Blok add-on (v0.1.0rc3) is installed and enabled on a new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to a website that track user actions.
2. Click on the Blok icon in the address bar.
3. Click on the "Report a problem" button and observe the panel.

[Expected result]:
- The "Submit" button is placed at the bottom of the panel.

[Actual result]:
- The "Submit" button is missing.

[Notes]:
- Added a screenshot with the issue:
blok_issue_submit_button

### PR DESCRIPTION
**Pull request by groovecoder**
This fixes #147 by moving the "breakage notes" text area into a new 3rd panel that is shown after the user submits the first breakage feedback.

This also means there are now 2 separate `event: "submit"` telemetry pings sent for feedback. E.g.,
```
{"originDomain":"github.com","trackerDomains":["www.google-analytics.com"],"event":"submit","breakage":"images","notes":""}
```
and
```
{"originDomain":"github.com","trackerDomains":["www.google-analytics.com"],"event":"submit","breakage":"images","notes":"All the avatars are missing."}
```

So if this solution looks good for Fx 49, we will need to update `docs/metrics.md` and get fresh approvals there. (@clouserw)

### CODE REVIEW

**Comment by groovecoder** [comment]
Screenshots in Firefox 49 ...

blok-padded-github-main-panel

blok-padded-github-feedback-panel

blok-padded-github-breakage-notes-panel

blok-padded-github-main-panel-with-report

**Comment by johngruen** [comment]
wfm, @clouserw you might want to take a look at the ping format

**Comment by groovecoder** [comment]
@pdehaan or @rbillings: can you install https://github.com/mozilla/blok/blob/4ed057cd9f884b2e88b1e17da83b11c6400042ec/web-ext-artifacts/blok-1.0rc7.xpi?raw=true from this branch and see if I've over-looked anything before I merge?

**Comment by groovecoder** [comment]
@pdehaan @rbillings: *in Firefox 49* please

**Comment by groovecoder** [comment]
Fixed in https://github.com/mozilla/blok/pull/148/commits/44f47c4b4fc6633657e7bc0755e8c640b4c51841 included in https://github.com/mozilla/blok/pull/148. Please check there.

**Comment by pdehaan** [comment]
macOS El Capitan w/ Firefox Nightly 51.0a1 (2016-09-12), and my panel height is slightly taller than your screenshots:

fix__147__breakage-notes-panel_for_single_height_by_groovecoder_ _pull_request__148_ _mozilla_blok_ _github_and_fix__147__breakage-notes-panel_for_single_height_by_groovecoder_ _pull_request__148_ _mozilla_blok

**Comment by groovecoder** [comment]
It's an effect of Firefox 50+ dynamically adjusting pageAction pop-up heights. 😐 I wonder if there's a way I can detect Fx50+ and remove the padding that I added for Fx49

**Comment by groovecoder** [comment]
`runtime.getBrowserInfo()` will be available ... in Firefox 51+. 😢 

@johngruen is it okay to ship with the extra space in Firefox 50+, and then when Firefox 50 is landing in release - assuming Blok is still running by then - we'll ship an update to revert this padding/spacing hack?

**Comment by pdehaan** [comment]
Looks good in my local FF49 :+1:

blank_skitch_document

menubar_and_blok_blok-1_0rc8_xpi_at_b8f35caceae9ee81edcfb3faa3a7a4191cd994db_ _mozilla_blok_ _github

**Comment by pdehaan** [comment]
I think only other thing I noticed (now that it's a 3 page submission process), is that if I do:

1. Click [Report a Problem].
2. Select "Something else".
3. Click [Submit]
4. Click the `<` button in the upper-left corner of doorhanger.

Clicking the back button during page 3 takes you back to page 1, not page 2.

blok_blok-1_0rc8_xpi_at_b8f35caceae9ee81edcfb3faa3a7a4191cd994db_ _mozilla_blok_ _github

**Comment by groovecoder** [comment]
Good catch. Fixed in https://github.com/mozilla/blok/pull/148/commits/cdaad50a2d08d94ac1467b85c55b4a839faf0533 including a new rc9.xpi file.

**Comment by pdehaan** [comment]
Looks good. I notice that if I initiate a report, then go back, I lose the ability to toggle Tracking protection:

reddit__the_front_page_of_the_internet

**Comment by pdehaan** [comment]
Very clumsy video, but I was eventually to get back into that state of not being able to toggle tracking protection.

blok-148

**Comment by pdehaan** [comment]
Filed the disappearing toggle issue as https://github.com/mozilla/blok/issues/151.

I think this is :+1: to land (and bump the XPI on testpilot.dev.mozaws.net), unless anybody objects.

**Comment by groovecoder** [comment]
Merged and updated http://testpilot.dev.mozaws.net/experiments/blok to point to latest rc9.xpi.

**Pull request merged**
