### PR TITLE
for #69: trim out more images

### PR DESCRIPTION
**Pull request by groovecoder**
Saves another 26K
```
-rw-r--r--  1 lcrouch  staff   157K Sep  8 17:20 blok-1.0rc2.xpi
-rw-r--r--  1 lcrouch  staff   131K Sep  8 17:24 blok-1.0rc3.xpi
```

### CODE REVIEW

**Comment by groovecoder** [comment]
```
-rw-r--r--  1 lcrouch  staff   157K Sep  8 17:20 blok-1.0rc2.xpi
-rw-r--r--  1 lcrouch  staff   131K Sep  8 17:24 blok-1.0rc3.xpi
```

**Comment by pdehaan** [comment]
👍 I like your style, kid!
We've managed to reduce the add-on size by ~82% today.

```
-rw-r--r--  1 lcrouch  staff   753K Sep  8 13:52 blok-1.0rc1.xpi
-rw-r--r--  1 lcrouch  staff   157K Sep  8 14:06 blok-1.0rc2.xpi
-rw-r--r--  1 lcrouch  staff   131K Sep  8 17:24 blok-1.0rc3.xpi
```

**Comment by pdehaan** [comment]
Also, we could shave a few KB off the XPI by reducing/removing the spacing in the JSON files:


| FILE | SIZE | SPACES |
|:----|----:|:----:|
| disconnect-blocklist.json | 260K | 4 **(current)**
| disconnect-blocklist.2.json | 179K | 2
| disconnect-blocklist.0.json | 88K | one line/minimized
| disconnect-entitylist.json | 196K | 4 **(current)**
| disconnect-entitylist.2.json | 154K | 2
| disconnect-entitylist.0.json | 100K | one line/minimized

So by minimizing the JSON before packaging, we go from **~456K** (260+196) to **~188K** (88+100) &mdash; or roughly 41% of the original size.

Then again, the files are zipped, so probably not a huge deal.

---

Ah, here are the rough results of me running `npm run build` with 4, 2, and 0 spaces in the src/js/*.json files

```sh
157K -- blok-1.0rc2.xpi                                     # 4 spaces (current)
147K -- tracking_protection_experiment-1.0rc2.zip           # 2 spaces
144K -- tracking_protection_experiment-1.0rc2.no-spaces.zip # minimized
```

**Comment by pdehaan** [comment]
@groovecoder: Feel free to merge at your leisure. Everything looks good to me.

I moved my silly JSON minification micro-optimization (saves ~13KB from XPI, at the expense of unreadable JSON), so we can track that separately and not block this solid PR.

**Pull request merged**
