### PR TITLE
fix #72: feedback: breakage required error message

### LINKED ISSUE #72: Add Required Field error messages to modal
If a user neglects to select a radio button but enters text & clicks Submit the modal does not display any error messages [nor does it submit].

### PR DESCRIPTION
**Pull request by groovecoder**

### CODE REVIEW

**Comment by groovecoder** [comment]
@rbillings - you could review this fix by installing the signed .xpi in this PR:

https://github.com/mozilla/blok/blob/1bdaf5f14826badaf284c7543790b05356e66449/web-ext-artifacts/blok-0.1.9-fx.xpi

**Comment by rbillings** [comment]
With the updated .xpi I was able to see the required fields error, however I am no longer able to click the works well/problem buttons on any tab except the first one.

**Comment by groovecoder** [comment]
I wasn't able to reproduce that issue. What are the details about # of windows, # of tabs, which websites you're visiting, etc. ?

**Comment by rbillings** [comment]
I am no longer able to reproduce this. It was on Dev Ed., single window, up to 5 tabs, a ton of different websites. I'll keep my eye on this and if it doesn't repro over the next day or two I'll close the issue.

**Comment by groovecoder** [comment]
Okay, I'll merge here now. If you see it again, you can re-open the issue.

**Pull request merged**
